apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

# Container image for testing in staging env, likely uploaded by CI pipeline
images:
  - name: europe-north1-docker.pkg.dev/default-418011/docker-repo/node-hostname
    newTag: 20260520-1419-9a5d500

# Made up patches for staging env
patches:
  - patch: |-
      - op: remove
        path: /spec/template/spec/affinity
      - op: remove
        path: /spec/template/spec/containers/0/resources
      - op: add
        path: /spec/template/spec/containers/0/env/-
        value:
          name: ENVIRONMENT
          value: staging
    target:
      kind: Deployment
      name: node-hostname